version: '3.9'
services:
  postgres:
    image: postgres:15.2-alpine
    container_name: 'fullWithNest'
    environment:
      POSTGRES_DB: 'fullWithNest'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '5433:5433'
